import { useEffect } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import type { Note } from '../types'

/**
 * Polls GET /notes every 3 seconds while any non-local document note
 * has thumbnailUrl === null (thumbnail not yet generated by backend).
 */
export function useThumbnailPoller(notes: Note[]) {
  const queryClient = useQueryClient()

  const hasPending = notes.some(n =>
    !n.isLocal &&
    n.objects.some(o => o.type === 'document' && o.thumbnailUrl === null)
  )

  useEffect(() => {
    if (!hasPending) return
    const id = setInterval(() => {
      queryClient.invalidateQueries({ queryKey: ['notes'] })
    }, 3000)
    return () => clearInterval(id)
  }, [hasPending, queryClient])
}
